# Generated by Django 5.1.15 on 2026-03-03 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventtype_owning_program'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SRECategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_fr', models.CharField(blank=True, default='', help_text='French name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True, default='', help_text='French description')),
                ('severity', models.IntegerField(choices=[(1, 'Level 1 — Immediate'), (2, 'Level 2 — Within 24 hours'), (3, 'Level 3 — Within 7 days')], default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SRE category',
                'verbose_name_plural': 'SRE categories',
                'db_table': 'sre_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_sre',
            field=models.BooleanField(default=False, help_text='Flag this event as a Serious Reportable Event (SRE).', verbose_name='Serious Reportable Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='sre_flagged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Flagged at'),
        ),
        migrations.AddField(
            model_name='event',
            name='sre_flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sre_flagged_events', to=settings.AUTH_USER_MODEL, verbose_name='Flagged by'),
        ),
        migrations.AddField(
            model_name='event',
            name='sre_notifications_sent',
            field=models.BooleanField(default=False, verbose_name='SRE notifications sent'),
        ),
        migrations.AddField(
            model_name='event',
            name='sre_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.srecategory', verbose_name='SRE category'),
        ),
    ]
