# Generated by Django 5.1.15 on 2026-02-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0008_funder_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('push', 'Push (KoNote → ODK)'), ('pull', 'Pull (ODK → KoNote)'), ('both', 'Both directions')], max_length=10)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial — some errors'), ('failed', 'Failed')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('participants_pushed', models.IntegerField(default=0)),
                ('groups_pushed', models.IntegerField(default=0)),
                ('app_users_synced', models.IntegerField(default=0)),
                ('attendance_records_created', models.IntegerField(default=0)),
                ('notes_created', models.IntegerField(default=0)),
                ('submissions_skipped', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_details', models.TextField(blank=True, default='')),
                ('programs_synced', models.TextField(blank=True, default='', help_text='Comma-separated program IDs included in this sync.')),
            ],
            options={
                'verbose_name': 'sync run',
                'verbose_name_plural': 'sync runs',
                'db_table': 'field_collection_sync_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable offline field data collection for this program.')),
                ('data_tier', models.CharField(choices=[('restricted', 'Restricted — ID only'), ('standard', 'Standard — ID + first name'), ('field', 'Field — ID + first name + last initial'), ('field_contact', 'Field+Contact — ID + name + last initial + phone')], default='standard', help_text='Controls what participant data is available on field devices. Higher tiers expose more PII and require stricter device policies.', max_length=20)),
                ('profile', models.CharField(choices=[('group', 'Group Programs — session attendance'), ('home_visiting', 'Home Visiting — visit notes'), ('circle', 'Circle Programs — visit notes + circle observations'), ('full_field', 'Full Field — all forms')], default='home_visiting', help_text='Determines which forms are available to field staff.', max_length=20)),
                ('form_session_attendance', models.BooleanField(default=False)),
                ('form_visit_note', models.BooleanField(default=True)),
                ('form_circle_observation', models.BooleanField(default=False)),
                ('odk_project_id', models.IntegerField(blank=True, help_text='ODK Central project ID. Set automatically by sync_odk.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_config', to='programs.program')),
            ],
            options={
                'verbose_name': 'field collection configuration',
                'verbose_name_plural': 'field collection configurations',
                'db_table': 'field_collection_program_config',
            },
        ),
    ]
