# Generated by Django 6.0.1 on 2026-02-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnote',
            name='follow_up_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the follow-up was completed (new note recorded).', null=True),
        ),
        migrations.AddField(
            model_name='progressnote',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='Optional date to follow up on this note.', null=True),
        ),
    ]
