# Generated by Django 6.0.1 on 2026-02-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_add_interaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressnote',
            name='interaction_type',
            field=models.CharField(choices=[('session', 'One-on-One Session'), ('group', 'Group Session'), ('phone', 'Phone Call'), ('collateral', 'Contact with Others'), ('home_visit', 'Home Visit'), ('admin', 'Admin / Paperwork'), ('other', 'Other')], db_index=True, default='session', max_length=20),
        ),
    ]
