# Generated by Django 5.1.15 on 2026-02-17 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_progressnotetemplate_name_fr_and_more'),
        ('programs', '0008_funder_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('addressed', 'Addressed'), ('wont_do', "Won't Do")], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('noted', 'Noted'), ('important', 'Important'), ('urgent', 'Urgent')], default='noted', max_length=20)),
                ('addressed_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_suggestion_themes', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_themes', to='programs.program')),
            ],
            options={
                'db_table': 'suggestion_themes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_linked', models.BooleanField(default=False)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_links_created', to=settings.AUTH_USER_MODEL)),
                ('progress_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_links', to='notes.progressnote')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='notes.suggestiontheme')),
            ],
            options={
                'db_table': 'suggestion_links',
            },
        ),
        migrations.AddIndex(
            model_name='suggestiontheme',
            index=models.Index(fields=['program', 'status'], name='idx_theme_program_status'),
        ),
        migrations.AddIndex(
            model_name='suggestionlink',
            index=models.Index(fields=['theme'], name='idx_link_theme'),
        ),
        migrations.AddIndex(
            model_name='suggestionlink',
            index=models.Index(fields=['progress_note'], name='idx_link_note'),
        ),
        migrations.AddConstraint(
            model_name='suggestionlink',
            constraint=models.UniqueConstraint(fields=('theme', 'progress_note'), name='unique_theme_note_link'),
        ),
    ]
