# Generated by Django 5.1.15 on 2026-02-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_suggestion_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestiontheme',
            name='priority',
            field=models.CharField(choices=[('noted', 'Noted'), ('important', 'Important'), ('urgent', 'Urgent')], default='noted', help_text='Auto-calculated from linked suggestions via recalculate_theme_priority(). Do not set manually.', max_length=20),
        ),
    ]
