# Generated by Django 5.1.15 on 2026-02-18 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_alter_suggestiontheme_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestiontheme',
            name='keywords',
            field=models.TextField(blank=True, default='', help_text='Comma-separated keywords for lightweight auto-linking.'),
        ),
        migrations.AddField(
            model_name='suggestiontheme',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai_generated', 'AI Generated')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='suggestiontheme',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suggestion_themes', to=settings.AUTH_USER_MODEL),
        ),
    ]
