# Generated by Django 5.1.15 on 2026-02-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_case_insensitive_theme_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnote',
            name='alliance_rater',
            field=models.CharField(blank=True, choices=[('client', 'Participant self-rated'), ('worker_observed', 'Worker observed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='progressnote',
            name='alliance_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, "I don't feel heard by my worker"), (2, "My worker and I aren't on the same page"), (3, "We're working okay together"), (4, 'My worker gets what I need'), (5, 'I really trust my worker')], null=True),
        ),
        migrations.AlterField(
            model_name='progressnote',
            name='engagement_observation',
            field=models.CharField(blank=True, choices=[('disengaged', 'Not participating'), ('motions', 'Going through motions'), ('guarded', 'Guarded'), ('engaged', 'Engaged'), ('valuing', 'Fully invested'), ('no_interaction', 'No 1-on-1')], default='', max_length=20),
        ),
    ]
