# Generated by Django 5.1.15 on 2026-02-24 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
        ('notes', '0019_alliance_rating_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnote',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_notes', to='circles.circle'),
        ),
    ]
