# Generated by Django 5.1.15 on 2026-02-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_progressnote_circle'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnote',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Session duration in minutes.', null=True),
        ),
        migrations.AddField(
            model_name='progressnote',
            name='modality',
            field=models.CharField(blank=True, choices=[('in_person', 'In Person'), ('phone', 'Phone'), ('video', 'Video'), ('email_text', 'Email/Text')], help_text='How the session was delivered.', max_length=20, null=True),
        ),
    ]
