# Generated by Django 5.1.15 on 2026-02-25 02:35

from django.db import migrations, models


def convert_null_modality(apps, schema_editor):
    """Convert NULL modality values to empty string."""
    ProgressNote = apps.get_model("notes", "ProgressNote")
    ProgressNote.objects.filter(modality__isnull=True).update(modality="")


def reverse_null_modality(apps, schema_editor):
    """Reverse: convert empty modality back to NULL."""
    ProgressNote = apps.get_model("notes", "ProgressNote")
    ProgressNote.objects.filter(modality="").update(modality=None)


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0021_add_duration_and_modality'),
    ]

    operations = [
        # Convert existing NULL values to empty string before changing the field
        migrations.RunPython(convert_null_modality, reverse_null_modality),
        migrations.AlterField(
            model_name='progressnote',
            name='modality',
            field=models.CharField(blank=True, choices=[('in_person', 'In Person'), ('phone', 'Phone'), ('video', 'Video'), ('email_text', 'Email/Text')], default='', help_text='How the session was delivered.', max_length=20),
        ),
    ]
