# Generated by Django 5.1.15 on 2026-02-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0021_add_duration_and_modality'),
    ]

    operations = [
        # Convert existing NULL values to empty string before changing the field
        migrations.RunSQL(
            sql="UPDATE notes_progressnote SET modality = '' WHERE modality IS NULL;",
            reverse_sql="UPDATE notes_progressnote SET modality = NULL WHERE modality = '';",
        ),
        migrations.AlterField(
            model_name='progressnote',
            name='modality',
            field=models.CharField(blank=True, choices=[('in_person', 'In Person'), ('phone', 'Phone'), ('video', 'Video'), ('email_text', 'Email/Text')], default='', help_text='How the session was delivered.', max_length=20),
        ),
    ]
