# Generated by Django 5.1.15 on 2026-02-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0022_fix_modality_null_to_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnote',
            name='author_role',
            field=models.CharField(blank=True, default='', help_text='Auto-filled from UserProgramRole at note creation.', max_length=30),
        ),
    ]
