# Generated by Django 5.1.15 on 2026-03-03 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0024_backfill_author_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metricvalue',
            name='plausibility_confirmed',
            field=models.BooleanField(default=False, help_text='True if staff confirmed a value outside the plausibility warning range.'),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='plausibility_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plausibility_overrides', to=settings.AUTH_USER_MODEL),
        ),
    ]
