# Generated by Django 5.1.15 on 2026-03-03 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0025_plausibility_warnings'),
        ('plans', '0018_set_financial_warn_thresholds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlausibilityOverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_value', models.FloatField(help_text='The value that triggered the plausibility warning')),
                ('threshold_type', models.CharField(choices=[('warn_min', 'Below minimum'), ('warn_max', 'Above maximum')], max_length=20)),
                ('threshold_value', models.FloatField(help_text='The warn_min or warn_max value that was breached')),
                ('action', models.CharField(choices=[('confirmed', 'Staff confirmed the value'), ('corrected', 'Staff corrected the value')], max_length=20)),
                ('corrected_value', models.FloatField(blank=True, help_text='The corrected value, if changed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plausibility_overrides', to='plans.metricdefinition')),
                ('progress_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plausibility_overrides', to='notes.progressnote')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'plausibility override log',
                'verbose_name_plural': 'plausibility override logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
