# Generated by Django 5.1.15 on 2026-03-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0026_plausibilityoverridelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnote',
            name='alliance_prompt_index',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Which alliance prompt set was shown (index into ALLIANCE_PROMPT_SETS).', null=True),
        ),
    ]
