# Generated by Django 5.1.15 on 2026-03-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0027_progressnote_alliance_prompt_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressnote',
            name='note_type',
            field=models.CharField(choices=[('quick', 'Quick Note'), ('full', 'Detailed Note'), ('assessment', 'Assessment')], max_length=20),
        ),
    ]
