# Generated by Django 5.1.15 on 2026-03-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0028_alter_progressnote_note_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricvalue',
            name='value',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
