# Generated by Django 5.1.15 on 2026-03-03 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0009_program_cids_sector_code_program_description_fr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsortiumMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consortium_id', models.IntegerField(help_text='FK to tenants.Consortium in the shared schema.')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'consortium_memberships',
            },
        ),
        migrations.CreateModel(
            name='PublishedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('data_json', models.JSONField(help_text='Aggregate report data (de-identified, n<5 cells suppressed).')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_reports', to='consortia.consortiummembership')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'published_reports',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics_shared', models.JSONField(blank=True, default=list, help_text='List of metric definition IDs shared with this consortium.')),
                ('date_from', models.DateField(help_text='Data shared from this date onward.')),
                ('date_to', models.DateField(blank=True, help_text='Data shared until this date. Null = ongoing.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_shares', to='consortia.consortiummembership')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consortium_shares', to='programs.program')),
            ],
            options={
                'db_table': 'program_sharing',
                'unique_together': {('membership', 'program')},
            },
        ),
    ]
