# Generated by Django 5.1.15 on 2026-02-24 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0024_alter_clientfile_cross_program_sharing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name_encrypted', models.BinaryField(default=b'')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_demo', models.BooleanField(default=False, help_text='Demo circles are only visible to demo users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_circles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'circles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CircleMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, default='', max_length=255)),
                ('relationship_label', models.CharField(blank=True, default='', help_text='Free text — e.g. parent, spouse, sibling, grandparent.', max_length=100)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='circles.circle')),
                ('client_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circle_memberships', to='clients.clientfile')),
            ],
            options={
                'db_table': 'circle_memberships',
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_file__isnull', False), ('status', 'active')), fields=('circle', 'client_file'), name='unique_circle_client_file')],
            },
        ),
    ]
