# Generated by Django 5.1.15 on 2026-02-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circlemembership',
            name='member_name',
        ),
        migrations.AddField(
            model_name='circlemembership',
            name='_member_name_encrypted',
            field=models.BinaryField(default=b''),
        ),
    ]
