"""Template-driven report generation engine.

Orchestrates data collection and output formatting for template-driven
reports.  Delegates to generate_funder_report_data() for the heavy
lifting and applies suppression / formatting on top.

When the template has ReportMetric records with aggregation rules,
uses compute_template_metrics() for the metric-rows × demographic-columns
format specified in the DRR.  Falls back to legacy CSV format when no
ReportMetric records exist.

Separation from funder_report.py ensures the template pipeline cannot
accidentally fall back to flat ad-hoc output.

See tasks/design-rationale/reporting-architecture.md for the full spec.
"""
import csv
import io
import json
import logging
from datetime import date, datetime, time

from django.utils import timezone
from django.utils.translation import gettext as _

from apps.clients.models import ClientProgramEnrolment
from apps.notes.models import ProgressNote

from .aggregation import compute_template_metrics
from .cids_jsonld import build_cids_jsonld_document
from .csv_utils import sanitise_csv_row, sanitise_filename
from .funder_report import (
    generate_funder_report_csv_rows,
    generate_funder_report_data,
    get_demographic_groups,
)
from .models import ReportMetric, ReportSection
from .suppression import (
    SMALL_CELL_THRESHOLD,
    apply_secondary_suppression,
    suppress_small_cell,
)

logger = logging.getLogger(__name__)


def _get_active_client_ids(program, date_from, date_to, user=None):
    """Get IDs of clients with activity in the reporting period.

    Mirrors the logic in generate_funder_report_data() (lines 221–277)
    but returns just the IDs for use by get_demographic_groups().
    """
    from apps.clients.models import ClientFile
    from django.db.models import Q

    enrolled_client_ids = list(
        ClientProgramEnrolment.objects.filter(
            program=program, status="active",
        ).values_list("client_file_id", flat=True)
    )

    if user is not None:
        if user.is_demo:
            accessible_ids = set(
                ClientFile.objects.demo().values_list("pk", flat=True)
            )
        else:
            accessible_ids = set(
                ClientFile.objects.real().values_list("pk", flat=True)
            )
        enrolled_client_ids = [
            cid for cid in enrolled_client_ids if cid in accessible_ids
        ]

    date_from_dt = timezone.make_aware(datetime.combine(date_from, time.min))
    date_to_dt = timezone.make_aware(datetime.combine(date_to, time.max))

    active_client_ids = list(
        ProgressNote.objects.filter(
            client_file_id__in=enrolled_client_ids,
            status="default",
        ).filter(
            Q(backdate__range=(date_from_dt, date_to_dt))
            | Q(backdate__isnull=True, created_at__range=(date_from_dt, date_to_dt))
        ).values_list("client_file_id", flat=True).distinct()
    )
    return active_client_ids


def generate_template_csv_rows(
    template,
    report_data,
    metric_results,
    demographic_labels,
    period_label,
    user,
):
    """Produce CSV rows in the DRR-specified metric-rows × demographic-columns format.

    Uses the template's suppression_threshold and applies secondary
    suppression so that no suppressed cell can be derived by subtraction.

    Output format (from reporting-architecture.md):
        Report: United Way Quarterly Outcome Report
        Program: Youth Employment Services
        Period: Q3 FY2025-26 (Oct 1 – Dec 31, 2025)
        ...
        Suppression threshold: < 5

        Metric,All Participants,Age 13-17,Age 18-24,Age 25+
        Youth Engagement Index (mean),3.8,3.2,4.1,3.9
        Youth Engagement Index (n),50,12,28,10
        Goal Achievement Rate (%),64%,50%,71%,60%

    Args:
        template: ReportTemplate instance.
        report_data: Dict from generate_funder_report_data() (for metadata).
        metric_results: List from compute_template_metrics().
        demographic_labels: Ordered list of demographic group labels (column headers).
        period_label: Human-readable period string.
        user: Requesting user (for "generated by" line).

    Returns:
        List of lists (CSV rows).
    """
    threshold = getattr(template, "suppression_threshold", SMALL_CELL_THRESHOLD)
    rows = []

    # Metadata header
    rows.append([f"{_('Report')}: {template.partner.translated_name} — {template.name}"])
    rows.append([f"{_('Program')}: {report_data.get('program_name', '')}"])
    rows.append([f"{_('Period')}: {period_label}"])

    generated_at = report_data.get("generated_at", timezone.now())
    if hasattr(generated_at, "strftime"):
        rows.append([f"{_('Generated')}: {generated_at.strftime('%Y-%m-%d')}"])
    else:
        rows.append([f"{_('Generated')}: {generated_at}"])

    display_name = getattr(user, "display_name", str(user)) if user else ""
    rows.append([f"{_('Generated by')}: {display_name}"])
    rows.append([f"{_('Template')}: {template.name}"])
    rows.append([f"{_('Suppression threshold')}: < {threshold}"])
    rows.append([])  # blank separator

    # Service statistics
    rows.append([_("Service Statistics")])
    rows.append([
        _("Total Individuals Served"),
        report_data.get("total_individuals_served", 0),
    ])
    rows.append([
        _("New Participants This Period"),
        report_data.get("new_clients_this_period", 0),
    ])
    rows.append([
        _("Total Service Contacts"),
        report_data.get("total_contacts", 0),
    ])
    rows.append([])

    # Metric table: metric-rows × demographic-columns
    if metric_results:
        header = [_("Metric")] + demographic_labels
        rows.append(header)

        for mr in metric_results:
            label = mr["label"]
            suffix = ""
            for group_label in demographic_labels:
                group_data = mr["values"].get(group_label, {})
                if group_data.get("label_suffix"):
                    suffix = f" {group_data['label_suffix']}"
                    break

            # Build value row with per-cell n values for suppression check
            raw_cells = []
            for group_label in demographic_labels:
                group_data = mr["values"].get(group_label, {})
                raw_cells.append((group_label, group_data.get("n", 0)))

            # Apply secondary suppression to the n-values
            suppressed_cells = apply_secondary_suppression(raw_cells, threshold)
            suppressed_map = dict(suppressed_cells)

            row = [f"{label}{suffix}"]
            for group_label in demographic_labels:
                group_data = mr["values"].get(group_label, {})
                value = group_data.get("value", "")
                cell_display = suppressed_map.get(group_label)
                if isinstance(cell_display, str) and cell_display.startswith("<"):
                    # This cell is suppressed
                    row.append(cell_display)
                elif mr["aggregation"] in ("threshold_percentage", "percentage"):
                    row.append(f"{value}%")
                else:
                    row.append(value)
            rows.append(row)

            # Add count row (n) for aggregation types that have a meaningful n
            if mr["aggregation"] in ("average", "threshold_percentage", "percentage"):
                n_row = [f"{label} (n)"]
                for group_label in demographic_labels:
                    cell_display = suppressed_map.get(group_label)
                    if isinstance(cell_display, str) and cell_display.startswith("<"):
                        n_row.append(cell_display)
                    else:
                        group_data = mr["values"].get(group_label, {})
                        n_row.append(group_data.get("n", 0))
                rows.append(n_row)

    return rows


def generate_template_report(template, date_from, date_to, period_label,
                             user, export_format, request, taxonomy_lens="iris_plus"):
    """
    Generate a template-driven report.

    Args:
        template: ReportTemplate instance (defines programs, metrics,
                  demographics, aggregation rules via Partner).
        date_from: Start of reporting period (date).
        date_to: End of reporting period (date).
        period_label: Human-readable period (e.g. "Q3 FY2025-26").
        user: Requesting user (for demo/real client filtering).
        export_format: "csv", "pdf", "html", or "cids_json".
        request: HttpRequest (needed by PDF renderer).

    Returns:
        Tuple of (content, filename, client_count):
        - content: str (CSV/HTML) or bytes (PDF)
        - filename: suggested download filename
        - client_count: raw integer count for SecureExportLink
    """
    threshold = getattr(template, "suppression_threshold", SMALL_CELL_THRESHOLD)
    programs = list(template.partner.get_programs())
    total_client_count = 0

    # Check if this template has ReportMetric records with aggregation rules
    report_metrics = list(
        ReportMetric.objects.filter(
            report_template=template,
        ).select_related("metric_definition").order_by("sort_order")
    )
    has_aggregation = bool(report_metrics)

    # Generate data per program
    all_report_data = []
    all_metric_results = []
    all_demographic_labels = []

    for program in programs:
        report_data = generate_funder_report_data(
            program,
            date_from=date_from,
            date_to=date_to,
            fiscal_year_label=period_label,
            user=user,
            report_template=template,
            taxonomy_lens=taxonomy_lens,
        )

        raw_count = report_data.get("total_individuals_served", 0)
        if isinstance(raw_count, int):
            total_client_count += raw_count

        # Apply small-cell suppression to service stats (unconditional
        # for funder reports — no program/is_confidential gate).
        report_data["total_individuals_served"] = suppress_small_cell(
            report_data["total_individuals_served"], threshold=threshold,
        )
        report_data["new_clients_this_period"] = suppress_small_cell(
            report_data["new_clients_this_period"], threshold=threshold,
        )

        # Apply suppression + secondary suppression to age demographics
        if "age_demographics" in report_data:
            age_cells = list(report_data["age_demographics"].items())
            suppressed_age = apply_secondary_suppression(age_cells, threshold)
            report_data["age_demographics"] = dict(suppressed_age)

        # Apply suppression to custom demographic sections
        if "custom_demographic_sections" in report_data:
            for section in report_data["custom_demographic_sections"]:
                section_cells = list(section["data"].items())
                suppressed_section = apply_secondary_suppression(
                    section_cells, threshold,
                )
                any_suppressed = any(
                    isinstance(v, str) for _, v in suppressed_section
                )
                section["data"] = dict(suppressed_section)
                if any_suppressed:
                    section["total"] = "suppressed"

        all_report_data.append((program, report_data))

        # Compute aggregated metrics per demographic group
        if has_aggregation and export_format != "cids_json":
            active_ids = _get_active_client_ids(program, date_from, date_to, user)
            demo_groups = get_demographic_groups(active_ids, date_to, template)
            metric_results = compute_template_metrics(
                program, date_from, date_to,
                report_metrics, demo_groups, user,
            )
            all_metric_results.append(metric_results)
            # Preserve demographic label order from the first program
            if not all_demographic_labels:
                all_demographic_labels = list(demo_groups.keys())

    is_multi_program = len(programs) > 1

    safe_partner = sanitise_filename(template.partner.name.replace(" ", "_"))
    safe_period = sanitise_filename(period_label.replace(" ", "_"))

    # Query ReportSection for PDF structuring (step 7)
    sections = list(
        ReportSection.objects.filter(
            report_template=template,
        ).order_by("sort_order")
    )

    if is_multi_program:
        content, filename = _render_multi_program(
            template=template,
            all_report_data=all_report_data,
            all_metric_results=all_metric_results,
            all_demographic_labels=all_demographic_labels,
            sections=sections,
            has_aggregation=has_aggregation,
            period_label=period_label,
            date_from=date_from,
            date_to=date_to,
            user=user,
            request=request,
            export_format=export_format,
            taxonomy_lens=taxonomy_lens,
            report_metrics=report_metrics,
            safe_partner=safe_partner,
            safe_period=safe_period,
        )
    else:
        _program, report_data = all_report_data[0]
        metric_results = all_metric_results[0] if all_metric_results else []

        if export_format == "pdf":
            from .pdf_views import generate_funder_report_pdf
            pdf_response = generate_funder_report_pdf(
                request, report_data,
                sections=sections if sections else None,
                metric_results=metric_results if metric_results else None,
            )
            filename = f"Report_{safe_partner}_{safe_period}.pdf"
            content = pdf_response.content
        elif export_format == "html":
            from .pdf_utils import render_html_string
            html_template = _get_html_template_name(template)
            html_context = _build_html_context(
                report_data, sections, metric_results, template, user,
            )
            content = render_html_string(html_template, html_context)
            filename = f"Report_{safe_partner}_{safe_period}.html"
        elif export_format == "cids_json":
            document = build_cids_jsonld_document(
                programs=[_program],
                taxonomy_lens=taxonomy_lens,
                date_from=date_from,
                date_to=date_to,
                metric_definitions=[rm.metric_definition for rm in report_metrics] if report_metrics else None,
            )
            content = json.dumps(document, indent=2, ensure_ascii=False)
            filename = f"Report_{safe_partner}_{safe_period}.jsonld"
        else:
            csv_buffer = io.StringIO()
            writer = csv.writer(csv_buffer)

            if has_aggregation and metric_results:
                csv_rows = generate_template_csv_rows(
                    template, report_data, metric_results,
                    all_demographic_labels, period_label, user,
                )
            else:
                csv_rows = generate_funder_report_csv_rows(report_data)

            for row in csv_rows:
                writer.writerow(sanitise_csv_row(row))
            filename = f"Report_{safe_partner}_{safe_period}.csv"
            content = csv_buffer.getvalue()

    return content, filename, total_client_count


def _render_multi_program(
    *,
    template,
    all_report_data,
    all_metric_results,
    all_demographic_labels,
    sections,
    has_aggregation,
    period_label,
    date_from,
    date_to,
    user,
    request,
    export_format,
    taxonomy_lens,
    report_metrics,
    safe_partner,
    safe_period,
):
    """Render a report that spans multiple programs.

    Produces per-program sections with an organisation-level summary.
    """
    from .utils import aggregate_all_programs_totals

    display_name = getattr(user, "display_name", str(user)) if user else ""
    threshold = getattr(template, "suppression_threshold", SMALL_CELL_THRESHOLD)

    # Build programs list with metric_results attached
    programs_with_data = []
    for i, (prog, rd) in enumerate(all_report_data):
        entry = {"name": prog.name, "report_data": rd}
        if all_metric_results and i < len(all_metric_results):
            entry["metric_results"] = all_metric_results[i]
        programs_with_data.append(entry)

    totals = aggregate_all_programs_totals(all_report_data)
    # Remove 'programs' from totals to avoid overwriting programs_with_data
    # (which includes metric_results and chart_images)
    totals.pop("programs", None)

    if sections:
        logger.info(
            "Template %r has %d ReportSection(s); multi-program reports "
            "use a summary layout — section-driven content (narrative, "
            "standards alignment) is included per program.",
            template.name, len(sections),
        )

    if export_format in ("html", "pdf"):
        from .pdf_utils import render_html_string
        from .chart_utils import generate_metric_charts, is_chart_available

        # Generate charts per program
        if is_chart_available():
            for prog_entry in programs_with_data:
                mr = prog_entry.get("metric_results")
                if mr:
                    prog_entry["chart_images"] = generate_metric_charts(mr)

        html_context = {
            "partner_name": template.partner.translated_name,
            "template_name": template.name,
            "period_label": period_label,
            "generated_at": timezone.now().strftime("%Y-%m-%d"),
            "generated_by": display_name,
            "programs": programs_with_data,
            "sections": sections,
            "suppression_threshold": threshold,
            **totals,
        }

        if export_format == "pdf":
            from .pdf_utils import is_pdf_available
            if is_pdf_available():
                from weasyprint import HTML as WeasyHTML
                html_str = render_html_string(
                    "reports/html_report_multi_program.html", html_context,
                )
                pdf_bytes = WeasyHTML(string=html_str).write_pdf()
                content = pdf_bytes
                filename = f"Report_{safe_partner}_{safe_period}.pdf"
            else:
                # WeasyPrint not available — fall back to HTML with correct extension
                content = render_html_string(
                    "reports/html_report_multi_program.html", html_context,
                )
                filename = f"Report_{safe_partner}_{safe_period}.html"
                logger.warning(
                    "WeasyPrint not available; multi-program PDF exported as HTML.",
                )
        else:
            content = render_html_string(
                "reports/html_report_multi_program.html", html_context,
            )
            filename = f"Report_{safe_partner}_{safe_period}.html"

    elif export_format == "cids_json":
        all_programs = [prog for prog, _rd in all_report_data]
        document = build_cids_jsonld_document(
            programs=all_programs,
            taxonomy_lens=taxonomy_lens,
            date_from=date_from,
            date_to=date_to,
            metric_definitions=[rm.metric_definition for rm in report_metrics] if report_metrics else None,
        )
        content = json.dumps(document, indent=2, ensure_ascii=False)
        filename = f"Report_{safe_partner}_{safe_period}.jsonld"

    else:
        # CSV: per-program sections
        csv_buffer = io.StringIO()
        writer = csv.writer(csv_buffer)

        # Organisation summary header
        writer.writerow(sanitise_csv_row([
            f"{_('Report')}: {template.partner.translated_name} — {template.name}",
        ]))
        writer.writerow(sanitise_csv_row([
            f"{_('Period')}: {period_label}",
        ]))
        writer.writerow(sanitise_csv_row([
            f"{_('Programs')}: {len(all_report_data)}",
        ]))
        writer.writerow(sanitise_csv_row([
            f"{_('Total Individuals Served')}: {totals['total_served']}",
        ]))
        writer.writerow([])

        for i, (prog, rd) in enumerate(all_report_data):
            metric_results = all_metric_results[i] if all_metric_results and i < len(all_metric_results) else []

            if has_aggregation and metric_results:
                csv_rows = generate_template_csv_rows(
                    template, rd, metric_results,
                    all_demographic_labels, period_label, user,
                )
            else:
                csv_rows = generate_funder_report_csv_rows(rd)

            # Override the program name row
            writer.writerow(sanitise_csv_row([
                f"{'=' * 40} {prog.name} {'=' * 40}",
            ]))
            for row in csv_rows:
                writer.writerow(sanitise_csv_row(row))
            writer.writerow([])

        filename = f"Report_{safe_partner}_{safe_period}.csv"
        content = csv_buffer.getvalue()

    return content, filename


def _get_html_template_name(template):
    """Return the Django template path for HTML export.

    If the ReportTemplate has a custom ``html_template_name`` set (for a
    partner-branded layout), use that.  Otherwise fall back to the default
    HTML report template which mirrors the PDF layout.
    """
    custom = getattr(template, "html_template_name", "")
    if custom:
        return custom
    return "reports/html_report.html"


def _build_html_context(report_data, sections, metric_results, template, user):
    """Build the template context dict for HTML report rendering.

    Mirrors the context produced by generate_funder_report_pdf() so that
    HTML and PDF templates receive the same data.
    """
    from .suppression import SMALL_CELL_THRESHOLD

    context = {
        "report_data": report_data,
        "generated_by": getattr(user, "display_name", str(user)) if user else "",
        "suppression_threshold": getattr(
            template, "suppression_threshold", SMALL_CELL_THRESHOLD,
        ),
    }

    if sections:
        context["sections"] = sections
    if metric_results:
        context["metric_results"] = metric_results

        from .chart_utils import generate_metric_charts, is_chart_available
        if is_chart_available():
            context["chart_images"] = generate_metric_charts(metric_results)

    return context


def get_compliance_summary(start_date, end_date):
    """
    Generate a privacy compliance summary for board reports.
    Returns a dict with aggregate counts -- no PII.

    ``start_date`` and ``end_date`` are ``date`` objects.  They are
    converted to timezone-aware ``datetime`` objects internally because
    the underlying model fields (``completed_at``, ``requested_at``) are
    ``DateTimeField``.
    """
    from datetime import timedelta

    from django.db.models import Avg, F

    from apps.clients.models import ErasureRequest

    # Convert date → timezone-aware datetime for DateTimeField queries
    start_dt = timezone.make_aware(datetime.combine(start_date, time.min))
    end_dt = timezone.make_aware(datetime.combine(end_date, time.max))

    # Completed erasure requests in the period
    completed = ErasureRequest.objects.filter(
        status="anonymised",
        completed_at__range=(start_dt, end_dt),
    )
    completed_count = completed.count()

    # Still pending at period end
    pending_at_end = ErasureRequest.objects.filter(
        status="pending",
        requested_at__lte=end_dt,
    ).count()

    if completed_count == 0 and pending_at_end == 0:
        return {"summary_text": _("No privacy requests were received this period.")}

    # Average processing time for completed requests
    avg_days = None
    if completed_count > 0:
        avg_result = completed.annotate(
            processing_time=F("completed_at") - F("requested_at")
        ).aggregate(avg=Avg("processing_time"))["avg"]
        avg_days = avg_result.days if avg_result else 0

    # Check if all completed within 30-day statutory deadline
    overdue_count = 0
    if completed_count > 0:
        overdue_count = completed.filter(
            completed_at__gt=F("requested_at") + timedelta(days=30)
        ).count()

    return {
        "completed_count": completed_count,
        "pending_at_end": pending_at_end,
        "avg_processing_days": avg_days,
        "overdue_count": overdue_count,
        "all_within_deadline": overdue_count == 0,
        "summary_text": _(
            "Privacy requests processed: %(count)d "
            "(average %(days)d days, %(deadline)s)"
        ) % {
            "count": completed_count,
            "days": avg_days or 0,
            "deadline": (
                _("all within statutory deadline")
                if overdue_count == 0
                else _("%(overdue)d exceeded 30-day statutory deadline")
                % {"overdue": overdue_count}
            ),
        } + (
            _(" — %(pending)d still pending at period end")
            % {"pending": pending_at_end}
            if pending_at_end > 0
            else ""
        ),
    }
