"""CSV output for the Sessions by Participant report.

Produces a self-documenting CSV with:
1. Metadata header (program, date range, generated date)
2. Per-session detail rows (one row per session)
3. Summary section with aggregates

Follows the existing CSV output patterns in csv_utils.py for
sanitisation and filename safety.

See tasks/session-reporting-research.md for field requirements.
"""
import csv
import io

from django.utils import timezone
from django.utils.translation import gettext as _

from .csv_utils import sanitise_csv_row, sanitise_filename


def generate_session_report_csv(report_data):
    """Generate CSV content from session report data.

    Args:
        report_data: dict returned by generate_session_report()

    Returns:
        tuple of (csv_content_string, suggested_filename)
    """
    metadata = report_data["metadata"]
    summary = report_data["summary"]
    sessions = report_data["sessions"]
    participants = report_data["participants"]

    rows = []

    # -- Metadata header --
    rows.append([_("Sessions by Participant Report")])
    rows.append([_("Program"), metadata["program_name"]])
    rows.append([
        _("Period"),
        f"{metadata['date_from']} {_('to')} {metadata['date_to']}",
    ])
    generated_at = metadata.get("generated_at", timezone.now())
    if hasattr(generated_at, "strftime"):
        rows.append([_("Generated"), generated_at.strftime("%Y-%m-%d %H:%M")])
    else:
        rows.append([_("Generated"), str(generated_at)])
    rows.append([_("Generated by"), metadata.get("generated_by", "")])
    rows.append([])  # blank separator

    # -- Session detail rows --
    rows.append([_("Session Details")])
    rows.append([
        _("Participant"),
        _("Last Name"),
        _("Session Date"),
        _("Session Type"),
        _("Duration (min)"),
        _("Modality"),
        _("Provider"),
    ])

    for s in sorted(sessions, key=lambda x: (x["client_last_name"], x["client_display_name"], x["session_date"])):
        rows.append([
            s["client_display_name"],
            s["client_last_name"],
            s["session_date"].isoformat() if s["session_date"] else "",
            s["session_type"],
            s["duration_minutes"] if s["duration_minutes"] else "",
            s["modality"],
            s["provider"],
        ])

    rows.append([])  # blank separator

    # -- Participant summary rows --
    rows.append([_("Participant Summary")])
    rows.append([
        _("Participant"),
        _("Last Name"),
        _("Total Sessions"),
        _("Contact Hours"),
        _("First Session"),
        _("Last Session"),
        _("Days in Program"),
    ])

    for p in participants:
        rows.append([
            p["client_display_name"],
            p["client_last_name"],
            p["total_sessions"],
            p["total_contact_hours"],
            p["first_session"].isoformat() if p["first_session"] else "",
            p["last_session"].isoformat() if p["last_session"] else "",
            p["days_in_program"],
        ])

    rows.append([])  # blank separator

    # -- Report-level aggregates --
    rows.append([_("Report Summary")])
    rows.append([_("Total Unique Participants"), summary["total_unique_participants"]])
    rows.append([_("Total Sessions"), summary["total_sessions"]])
    rows.append([_("Average Sessions per Participant"), summary["average_sessions_per_participant"]])
    rows.append([_("Total Contact Hours"), summary["total_contact_hours"]])
    rows.append([_("Average Contact Hours per Participant"), summary["average_contact_hours_per_participant"]])
    rows.append([])

    # -- Modality distribution --
    if summary["modality_distribution"]:
        rows.append([_("Sessions by Modality")])
        for modality, count in sorted(summary["modality_distribution"].items()):
            rows.append([modality, count])
        rows.append([])

    # -- Session type distribution --
    if summary["session_type_distribution"]:
        rows.append([_("Sessions by Type")])
        for stype, count in sorted(summary["session_type_distribution"].items()):
            rows.append([stype, count])

    # Write to CSV
    csv_buffer = io.StringIO()
    writer = csv.writer(csv_buffer)
    for row in rows:
        writer.writerow(sanitise_csv_row(row))

    # Build filename
    safe_program = sanitise_filename(
        metadata["program_name"].replace(" ", "_")
    )
    safe_from = metadata["date_from"].isoformat() if metadata["date_from"] else "start"
    safe_to = metadata["date_to"].isoformat() if metadata["date_to"] else "end"
    filename = f"Sessions_{safe_program}_{safe_from}_{safe_to}.csv"

    return csv_buffer.getvalue(), filename
