# Generated by Django 5.1.15 on 2026-02-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_staffmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmessage',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Flag this message as urgent — shown at top of inbox'),
        ),
    ]
