# Generated by Django 5.1.15 on 2026-02-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_staffportalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantuser',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantuser',
            name='password_reset_last_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantuser',
            name='password_reset_request_count',
            field=models.IntegerField(default=0, help_text='Requests this hour. Reset by scheduled task or hourly check.'),
        ),
        migrations.AddField(
            model_name='participantuser',
            name='password_reset_token_hash',
            field=models.CharField(blank=True, default='', help_text='Hashed 6-digit reset code. Never store plaintext.', max_length=128),
        ),
    ]
