# Generated by Django 5.1.15 on 2026-02-20 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_password_reset_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAssistedLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', help_text='URL-safe token, single use.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_login_tokens', to='portal.participantuser')),
            ],
            options={
                'db_table': 'portal_staff_assisted_login_tokens',
            },
        ),
    ]
