# Generated by Django 5.1.15 on 2026-02-27 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_seed_dv_sensitive_defaults'),
        ('portal', '0004_staffassistedlogintoken'),
        ('programs', '0008_funder_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_client_resource_links', to='clients.clientfile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client resource link',
                'verbose_name_plural': 'client resource links',
                'db_table': 'portal_client_resource_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_fr', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, default='')),
                ('description_fr', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_resource_links', to='programs.program')),
            ],
            options={
                'verbose_name': 'portal resource link',
                'verbose_name_plural': 'portal resource links',
                'db_table': 'portal_resource_links',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
