# Generated by Django 6.0.1 on 2026-02-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogramrole',
            name='role',
            field=models.CharField(choices=[('receptionist', 'Receptionist'), ('staff', 'Counsellor'), ('program_manager', 'Program Manager')], max_length=20),
        ),
    ]
