# Generated by Django 5.1.15 on 2026-02-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_funder_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='cids_sector_code',
            field=models.CharField(blank=True, default='', help_text='CIDS sector code from ICNPOsector or ESDCSector code list.', max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='description_fr',
            field=models.TextField(blank=True, default='', help_text='French description for bilingual CIDS exports.'),
        ),
        migrations.AddField(
            model_name='program',
            name='funder_program_code',
            field=models.CharField(blank=True, default='', help_text='Funder-assigned program identifier.', max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='population_served_codes',
            field=models.JSONField(blank=True, default=list, help_text='Population served codes from PopulationServed code list.'),
        ),
    ]
