# Generated by Django 5.1.15 on 2026-02-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_metricdefinition_definition_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdefinition',
            name='is_universal',
            field=models.BooleanField(default=False, help_text='Universal scale (Confidence, Progress, Wellbeing) shown prominently during goal creation.'),
        ),
    ]
