# Generated by Django 5.1.15 on 2026-02-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_add_is_universal_to_metricdefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdefinition',
            name='computation_type',
            field=models.CharField(blank=True, choices=[('', 'Manual entry'), ('session_count', 'Sessions attended this month')], default='', help_text='If set, value is computed automatically instead of manual entry.', max_length=30),
        ),
    ]
