# Generated by Django 5.1.15 on 2026-02-20 04:53

import re
from django.db import migrations

def fix_scale_metrics(apps, schema_editor):
    """
    Find all scale-based MetricDefinition records (e.g., 1-5, 1-10 scales)
    and ensure their min_value and max_value fields are correctly populated
    so they render as pills instead of text inputs.
    """
    MetricDefinition = apps.get_model("plans", "MetricDefinition")
    
    # Look for metrics that might be scales but are missing min/max
    metrics = MetricDefinition.objects.filter(
        min_value__isnull=True
    ) | MetricDefinition.objects.filter(
        max_value__isnull=True
    )
    
    for metric in metrics:
        name_lower = metric.name.lower()
        def_lower = metric.definition.lower()
        
        # Check for 1-5 scale
        if "1-5" in name_lower or "1 to 5" in name_lower or "1-5" in def_lower or "1 to 5" in def_lower:
            metric.min_value = 1.0
            metric.max_value = 5.0
            metric.save(update_fields=["min_value", "max_value"])
            continue
            
        # Check for 1-10 scale
        if "1-10" in name_lower or "1 to 10" in name_lower or "1-10" in def_lower or "1 to 10" in def_lower:
            metric.min_value = 1.0
            metric.max_value = 10.0
            metric.save(update_fields=["min_value", "max_value"])
            continue
            
        # Check for 1-3 scale
        if "1-3" in name_lower or "1 to 3" in name_lower or "1-3" in def_lower or "1 to 3" in def_lower:
            metric.min_value = 1.0
            metric.max_value = 3.0
            metric.save(update_fields=["min_value", "max_value"])
            continue

def reverse_fix_scale_metrics(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_metricdefinition_computation_type'),
    ]

    operations = [
        migrations.RunPython(fix_scale_metrics, reverse_fix_scale_metrics),
    ]
