# Generated by Django 5.1.15 on 2026-02-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_fix_scale_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricdefinition',
            name='is_universal',
            field=models.BooleanField(default=False, help_text='Universal scale (Goal Progress, Self-Efficacy, Satisfaction) shown prominently during goal creation.'),
        ),
    ]
