# Generated by Django 5.1.15 on 2026-02-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_partner_report_section_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdefinition',
            name='achievement_options',
            field=models.JSONField(blank=True, default=list, help_text='Options for achievement metrics, e.g. ["Employed", "In training", "Unemployed"].'),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='achievement_success_values',
            field=models.JSONField(blank=True, default=list, help_text='Which options count as achieved, e.g. ["Employed"].'),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='higher_is_better',
            field=models.BooleanField(default=True, help_text='False for metrics like PHQ-9 where lower is better.'),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='metric_type',
            field=models.CharField(choices=[('scale', 'Numeric scale'), ('achievement', 'Achievement')], default='scale', help_text='Scale = numeric value recorded repeatedly. Achievement = categorical, typically recorded once.', max_length=20),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='target_band_high_pct',
            field=models.FloatField(blank=True, help_text='Optional target for % in high band (scale metrics).', null=True),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='target_rate',
            field=models.FloatField(blank=True, help_text='Optional target % for achievement metrics (e.g. 70 for 70%).', null=True),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='threshold_high',
            field=models.FloatField(blank=True, help_text='High band boundary (scale metrics).', null=True),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='threshold_low',
            field=models.FloatField(blank=True, help_text='Low band boundary (scale metrics).', null=True),
        ),
    ]
