# Generated by Django 5.1.15 on 2026-02-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_set_universal_metric_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdefinition',
            name='cids_defined_by',
            field=models.CharField(blank=True, default='', help_text='URI of the organisation that defined this indicator (e.g., GIIN for IRIS+).', max_length=500),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='cids_has_baseline',
            field=models.CharField(blank=True, default='', help_text="Human-readable baseline description (e.g., 'Average score 3.2 at intake'). NOT a boolean.", max_length=255),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='cids_indicator_uri',
            field=models.CharField(blank=True, default='', help_text='CIDS indicator @id — CharField not URLField (URIs may use urn: schemes).', max_length=500),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='cids_theme_override',
            field=models.CharField(blank=True, default='', help_text='Admin override for CIDS theme derivation when auto-derivation is wrong.', max_length=50),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='cids_unit_description',
            field=models.CharField(blank=True, default='', help_text='Human-readable unit label for CIDS export (maps to cids:unitDescription).', max_length=255),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='iris_metric_code',
            field=models.CharField(blank=True, default='', help_text="IRIS+ metric code from IrisMetric53 code list (e.g., 'PI2061').", max_length=100),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='sdg_goals',
            field=models.JSONField(blank=True, default=list, help_text='List of SDG goal numbers [1–17].'),
        ),
        migrations.AddField(
            model_name='plantarget',
            name='cids_outcome_uri',
            field=models.CharField(blank=True, default='', help_text='CIDS outcome @id.', max_length=500),
        ),
    ]
