# Generated by Django 5.1.15 on 2026-02-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_metricdefinition_cids_defined_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantarget',
            name='achievement_status',
            field=models.CharField(blank=True, choices=[('in_progress', 'In progress'), ('improving', 'Improving'), ('worsening', 'Worsening'), ('no_change', 'No change'), ('achieved', 'Achieved'), ('sustaining', 'Sustaining'), ('not_achieved', 'Not achieved'), ('not_attainable', 'Not attainable')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='plantarget',
            name='achievement_status_source',
            field=models.CharField(blank=True, choices=[('auto_computed', 'Auto-computed'), ('worker_assessed', 'Worker assessed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='plantarget',
            name='achievement_status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantarget',
            name='first_achieved_at',
            field=models.DateTimeField(blank=True, help_text='When first achieved. Never cleared once set.', null=True),
        ),
    ]
