# Generated by Django 5.1.15 on 2026-03-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0016_session4_achievement_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdefinition',
            name='warn_max',
            field=models.FloatField(blank=True, help_text='Soft warning maximum — values above this trigger a plausibility warning but are still accepted.', null=True),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='warn_min',
            field=models.FloatField(blank=True, help_text='Soft warning minimum — values below this trigger a plausibility warning but are still accepted.', null=True),
        ),
    ]
