# Generated by Django 5.1.15 on 2026-03-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0020_set_financial_tier2_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdefinition',
            name='cadence_sessions',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How often to prompt for this metric (in sessions). Blank = every session.', null=True),
        ),
    ]
