# Generated by Django 5.1.15 on 2026-03-04 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0021_metricdefinition_cadence_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantargetmetric',
            name='assigned_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='plantargetmetric',
            name='last_reviewed_date',
            field=models.DateField(blank=True, help_text='When the worker last confirmed this metric is still relevant.', null=True),
        ),
    ]
