# Generated by Django 5.1.15 on 2026-03-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0022_plantargetmetric_assigned_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdefinition',
            name='assessment_at_discharge',
            field=models.BooleanField(default=False, help_text='Administer this assessment at discharge.'),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='assessment_at_intake',
            field=models.BooleanField(default=False, help_text='Administer this assessment at intake (first session).'),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='assessment_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days between scheduled administrations (e.g. 90 for quarterly). Global per-metric.', null=True),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='is_standardized_instrument',
            field=models.BooleanField(default=False, help_text='True for published validated instruments (PHQ-9, GAD-7, K10, etc.).'),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='rationale_log',
            field=models.JSONField(blank=True, default=list, help_text='Append-only changelog: [{date, note, note_fr, author}]. Most recent entry is the current rationale.'),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='scoring_bands',
            field=models.JSONField(blank=True, help_text='Published severity cutoffs, e.g. [{"label": "Minimal", "min": 0, "max": 4}]. Display-only.', null=True),
        ),
    ]
