# Generated by Django 5.1.15 on 2026-03-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0023_metricdefinition_assessment_at_discharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricdefinition',
            name='category',
            field=models.CharField(choices=[('mental_health', 'Mental Health'), ('housing', 'Housing'), ('employment', 'Employment'), ('substance_use', 'Substance Use'), ('youth', 'Youth'), ('general', 'General'), ('client_experience', 'Client Experience'), ('custom', 'Custom')], default='custom', max_length=30),
        ),
        migrations.AlterField(
            model_name='metricdefinition',
            name='metric_type',
            field=models.CharField(choices=[('scale', 'Numeric scale'), ('achievement', 'Achievement'), ('open_text', 'Open text')], default='scale', help_text='Scale = numeric value recorded repeatedly. Achievement = categorical, typically recorded once.', max_length=20),
        ),
    ]
