# Generated by Django 5.1.15 on 2026-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0028_plantarget_on_hold_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantarget',
            name='goal_source_method',
            field=models.CharField(blank=True, default='', help_text='How goal_source was derived: heuristic, worker_set, or ai_inferred.', max_length=20),
        ),
    ]
