# Generated by Django 5.1.15 on 2026-04-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0029_alter_plantarget_goal_source_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantarget',
            name='_action_steps_encrypted',
            field=models.BinaryField(blank=True, default=b''),
        ),
    ]
