# Generated by Django 5.1.15 on 2026-02-20 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('question_text_fr', models.CharField(blank=True, default='', max_length=1000)),
                ('question_type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('rating_scale', 'Rating scale'), ('short_text', 'Short text'), ('long_text', 'Long text'), ('yes_no', 'Yes / No')], max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('options_json', models.JSONField(blank=True, default=list, help_text='For choice questions: list of {value, label, label_fr, score}.')),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'survey_questions',
                'ordering': ['section', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_fr', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('description_fr', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False, help_text='If true, responses are never linked to a participant file.')),
                ('show_scores_to_participant', models.BooleanField(default=False, help_text='Whether participants see section scores after submission.')),
                ('portal_visible', models.BooleanField(default=True, help_text='Whether this survey appears in the participant portal.')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_fr', models.CharField(blank=True, default='', max_length=255)),
                ('instructions', models.TextField(blank=True, default='')),
                ('instructions_fr', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page_break', models.BooleanField(default=False, help_text='If true, this section starts a new page in the form.')),
                ('scoring_method', models.CharField(choices=[('none', 'No scoring'), ('sum', 'Sum'), ('average', 'Average')], default='none', max_length=10)),
                ('max_score', models.PositiveIntegerField(blank=True, null=True)),
                ('condition_value', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('condition_question', models.ForeignKey(blank=True, help_text='Section only shows when this question has the condition value.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_sections', to='surveys.surveyquestion')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys.survey')),
            ],
            options={
                'db_table': 'survey_sections',
                'ordering': ['survey', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.surveysection'),
        ),
    ]
