# Generated by Django 5.1.15 on 2026-02-20 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventtype_owning_program'),
        ('programs', '0008_funder_profiles'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTriggerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('event', 'Event'), ('enrolment', 'Enrolment'), ('time', 'Time-based'), ('characteristic', 'Characteristic')], max_length=20)),
                ('recurrence_days', models.PositiveIntegerField(blank=True, null=True)),
                ('anchor', models.CharField(choices=[('enrolment_date', 'Enrolment date'), ('last_completed', 'Last completion')], default='enrolment_date', max_length=20)),
                ('repeat_policy', models.CharField(choices=[('once_per_participant', 'Once per participant'), ('once_per_enrolment', 'Once per enrolment'), ('recurring', 'Recurring')], default='once_per_participant', max_length=25)),
                ('auto_assign', models.BooleanField(default=True, help_text='If true, assignment is automatic. If false, staff must approve.')),
                ('include_existing', models.BooleanField(default=False, help_text='When activated, also assign to participants who already match.')),
                ('is_active', models.BooleanField(default=True)),
                ('due_days', models.PositiveIntegerField(blank=True, help_text='Set a due date this many days after assignment.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_rules_created', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_trigger_rules', to='events.eventtype')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_trigger_rules', to='programs.program')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_rules', to='surveys.survey')),
            ],
            options={
                'db_table': 'survey_trigger_rules',
            },
        ),
    ]
