# Generated by Django 5.1.15 on 2026-02-20 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_fix_contact_field_ordering'),
        ('portal', '0002_staffportalnote'),
        ('surveys', '0002_surveytriggerrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_approval', 'Awaiting approval'), ('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('trigger_reason', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_assignments', to='clients.clientfile')),
                ('participant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_assignments', to='portal.participantuser')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='surveys.survey')),
                ('triggered_by_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='surveys.surveytriggerrule')),
            ],
            options={
                'db_table': 'survey_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('link', 'Shareable link'), ('portal', 'Participant portal'), ('staff_entered', 'Staff data entry')], max_length=20)),
                ('respondent_name_display', models.CharField(blank=True, default='', help_text='Optional name for link responses. Not encrypted (non-PII).', max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, default='', max_length=64)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='surveys.surveyassignment')),
                ('client_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='clients.clientfile')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
            ],
            options={
                'db_table': 'survey_responses',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_value_encrypted', models.BinaryField(blank=True, default=b'')),
                ('numeric_value', models.IntegerField(blank=True, help_text='For scales/scores. Stored as plain integer for aggregation.', null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse')),
            ],
            options={
                'db_table': 'survey_answers',
            },
        ),
        migrations.CreateModel(
            name='PartialAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_encrypted', models.BinaryField(default=b'')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_answers', to='surveys.surveyquestion')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_answers', to='surveys.surveyassignment')),
            ],
            options={
                'db_table': 'survey_partial_answers',
                'constraints': [models.UniqueConstraint(fields=('assignment', 'question'), name='unique_partial_answer_per_question')],
            },
        ),
    ]
