# Generated by Django 5.1.15 on 2026-03-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_surveylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveylink',
            name='single_response',
            field=models.BooleanField(default=False, help_text='If true, use a cookie to discourage multiple submissions from the same browser.'),
        ),
    ]
