# Generated by Django 5.1.15 on 2026-03-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_surveylink_single_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='consent_text',
            field=models.TextField(blank=True, default='', help_text='Consent text shown before the survey begins. The respondent must agree before proceeding. Leave blank to skip the consent step.'),
        ),
        migrations.AddField(
            model_name='survey',
            name='consent_text_fr',
            field=models.TextField(blank=True, default='', help_text='French consent text (displayed when language is French).'),
        ),
    ]
