# Generated by Django 5.1.15 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_survey_consent_text_survey_consent_text_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='consent_given_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When the respondent agreed to the consent text, if applicable.',
                null=True,
            ),
        ),
    ]
