# Generated by Django 5.1.15 on 2026-03-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_surveyresponse_consent_given_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='consent_withdrawn_at',
            field=models.DateTimeField(blank=True, help_text='When the respondent withdrew consent, if applicable.', null=True),
        ),
    ]
