# Generated by Django 5.1.15 on 2026-03-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_survey_source_surveysection_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysection',
            name='skip_for_identified',
            field=models.BooleanField(default=False, help_text='Hide this section when the survey is filled by or for an identified participant (portal or staff-entered). Use for demographics sections — that data is already in the participant record. Note: toggling this only affects future responses — existing responses are not retroactively changed.'),
        ),
    ]
