# Generated by Django 6.0.1 on 2026-02-03 01:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('programs', '0002_alter_userprogramrole_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('receptionist', 'Receptionist'), ('staff', 'Counsellor'), ('program_manager', 'Program Manager'), ('admin', 'Administrator')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Invite expires after this date.')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_created', to=settings.AUTH_USER_MODEL)),
                ('programs', models.ManyToManyField(blank=True, help_text='Programs to assign. Not used for admin invites.', to='programs.program')),
                ('used_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invites',
            },
        ),
    ]
