# Generated by Django 5.1.15 on 2026-02-25 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_rename_mfa_secret_to_encrypted'),
        ('clients', '0028_add_access_grant_reason_and_access_grant'),
        ('programs', '0008_funder_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGrantReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('label_fr', models.CharField(blank=True, default='', help_text='French translation. Leave blank to use English label.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'access_grant_reasons',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(help_text='Brief description of why access is needed.')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('client_file', models.ForeignKey(blank=True, help_text='If null, grant covers all clients in the program.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='clients.clientfile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='programs.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='auth_app.accessgrantreason')),
            ],
            options={
                'db_table': 'access_grants',
                'ordering': ['-granted_at'],
            },
        ),
    ]
