# Generated by Django 5.1.15 on 2026-03-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='tenant_schema',
            field=models.CharField(blank=True, default='', help_text='PostgreSQL schema name of the agency that generated this entry.', max_length=63),
        ),
    ]
