# Generated by Django 5.1.15 on 2026-02-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0002_add_french_terminology'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, default='', help_text='Required for CIDS BasicTier (org:hasLegalName).', max_length=255)),
                ('operating_name', models.CharField(blank=True, default='', help_text='Display name used in the application.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Mission statement or organisation description.')),
                ('description_fr', models.TextField(blank=True, default='', help_text='French mission statement for bilingual CIDS exports.')),
                ('legal_status', models.CharField(blank=True, default='', help_text='e.g., Registered charity, Nonprofit corporation.', max_length=100)),
                ('sector_codes', models.JSONField(blank=True, default=list, help_text='ICNPOsector codes for the organisation.')),
                ('street_address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(blank=True, choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], default='', max_length=2)),
                ('postal_code', models.CharField(blank=True, default='', help_text='Canadian format: A1A 1A1.', max_length=10)),
                ('country', models.CharField(default='CA', max_length=2)),
                ('website', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Organisation Profile',
                'db_table': 'organization_profiles',
            },
        ),
    ]
