# Generated by Django 5.1.15 on 2026-02-27 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0003_organizationprofile'),
        ('plans', '0015_metricdefinition_cids_defined_by_and_more'),
        ('programs', '0009_program_cids_sector_code_program_description_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CidsCodeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(help_text='Code list name, e.g., "ICNPOsector", "IrisMetric53".', max_length=100)),
                ('code', models.CharField(help_text='The code value within the list.', max_length=100)),
                ('label', models.CharField(help_text='Display label (English).', max_length=255)),
                ('label_fr', models.CharField(blank=True, default='', help_text='French label.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Longer description of the code.')),
                ('specification_uri', models.CharField(blank=True, default='', help_text='URI of code list spec (for SHACL cids:hasSpecification).', max_length=500)),
                ('defined_by_name', models.CharField(blank=True, default='', help_text='Defining organisation name (e.g., "GIIN", "United Nations").', max_length=255)),
                ('defined_by_uri', models.CharField(blank=True, default='', help_text='URI of defining organisation (for SHACL cids:definedBy).', max_length=500)),
                ('source_url', models.URLField(blank=True, default='', help_text='Common Approach code list page URL.')),
                ('version_date', models.DateField(blank=True, help_text='For staleness warnings.', null=True)),
            ],
            options={
                'verbose_name': 'CIDS Code List Entry',
                'verbose_name_plural': 'CIDS Code List Entries',
                'db_table': 'cids_code_lists',
                'ordering': ['list_name', 'code'],
                'unique_together': {('list_name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaxonomyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy_system', models.CharField(choices=[('cids_iris', 'CIDS / IRIS+'), ('united_way', 'United Way'), ('phac', 'Public Health Agency of Canada'), ('provincial', 'Provincial'), ('esdc', 'ESDC'), ('custom', 'Custom')], help_text='e.g., "cids_iris", "united_way", "phac".', max_length=50)),
                ('taxonomy_code', models.CharField(help_text='Code within the taxonomy system.', max_length=100)),
                ('taxonomy_label', models.CharField(blank=True, default='', help_text='Display label for the taxonomy code.', max_length=255)),
                ('funder_context', models.CharField(blank=True, default='', help_text='Which funder this mapping serves (blank = universal).', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomy_mappings', to='plans.metricdefinition')),
                ('plan_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomy_mappings', to='plans.plantarget')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxonomy_mappings', to='programs.program')),
            ],
            options={
                'verbose_name': 'Taxonomy Mapping',
                'db_table': 'taxonomy_mappings',
                'ordering': ['taxonomy_system', 'taxonomy_code'],
            },
        ),
    ]
