# Generated by Django 5.1.15 on 2026-02-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0004_cidscodelist_taxonomymapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='backup_last_exported_at',
            field=models.DateTimeField(blank=True, help_text='When the last backup export was completed.', null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='backup_reminder_contact_email',
            field=models.EmailField(blank=True, default='', help_text='Email address to send backup reminders to.', max_length=254),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='backup_reminder_enabled',
            field=models.BooleanField(default=False, help_text='Send periodic reminders when a backup export is due.'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='backup_reminder_frequency_days',
            field=models.IntegerField(default=90, help_text='How often to send backup reminders (in days).'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='backup_reminder_last_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the last backup reminder was sent.', null=True),
        ),
    ]
