# Generated by Django 5.1.15 on 2026-02-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_cross_program_sharing_tristate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfile',
            name='cross_program_sharing',
            field=models.CharField(choices=[('default', 'Follow agency setting'), ('consent', 'Share across programs'), ('restrict', 'Restrict to one program')], default='default', help_text='Controls whether clinical notes are visible across programs for this participant. Most participants use the agency default.', max_length=20),
        ),
    ]
