# Generated by Django 5.1.15 on 2026-02-25 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_alter_clientfile_cross_program_sharing'),
        ('clients', '0025_dataaccessrequest'),
    ]

    operations = [
    ]
