# Generated by Django 5.1.15 on 2026-02-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_merge_20260224_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldAccessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('front_desk_access', models.CharField(choices=[('none', 'Hidden'), ('view', 'View only'), ('edit', 'View and edit')], default='view', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'field_access_configs',
                'ordering': ['field_name'],
            },
        ),
    ]
