# Generated by Django 5.1.15 on 2026-02-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_add_field_access_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataaccessrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
