# Generated by Django 5.1.15 on 2026-02-25 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_add_access_grant_reason_and_access_grant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='is_dv_safe',
            field=models.BooleanField(default=False, help_text='When enabled, DV-sensitive custom fields (address, emergency contact, employer) are hidden from front desk staff for this participant.'),
        ),
        migrations.AddField(
            model_name='customfielddefinition',
            name='is_dv_sensitive',
            field=models.BooleanField(default=False, help_text='When checked, this field is hidden from front desk staff for participants with a DV safety flag.'),
        ),
        migrations.CreateModel(
            name='DvFlagRemovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(help_text='Explain why the DV safety flag should be removed.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, default=None, help_text='None = pending, True = approved (flag removed), False = rejected.', null=True)),
                ('review_note', models.TextField(blank=True, default='', help_text="Reviewer's note on approval or rejection.")),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dv_removal_requests', to='clients.clientfile')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dv_flag_removal_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
