# Generated by Django 5.1.15 on 2026-02-25 18:40

from django.db import migrations

# Default field names that should be marked DV-sensitive.
# Matched case-insensitively against CustomFieldDefinition.name.
DV_SENSITIVE_PATTERNS = [
    "address",
    "emergency contact",
    "emergency phone",
    "employer",
    "school",
    "workplace",
]


def mark_dv_sensitive_fields(apps, schema_editor):
    """Mark existing custom fields as DV-sensitive if their name matches."""
    CustomFieldDefinition = apps.get_model("clients", "CustomFieldDefinition")
    for field_def in CustomFieldDefinition.objects.all():
        name_lower = field_def.name.lower()
        for pattern in DV_SENSITIVE_PATTERNS:
            if pattern in name_lower:
                field_def.is_dv_sensitive = True
                field_def.save(update_fields=["is_dv_sensitive"])
                break


def unmark_dv_sensitive_fields(apps, schema_editor):
    """Reverse: clear all is_dv_sensitive flags."""
    CustomFieldDefinition = apps.get_model("clients", "CustomFieldDefinition")
    CustomFieldDefinition.objects.filter(is_dv_sensitive=True).update(is_dv_sensitive=False)


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_add_dv_safe_fields'),
    ]

    operations = [
        migrations.RunPython(mark_dv_sensitive_fields, unmark_dv_sensitive_fields),
    ]
