# Generated by Django 5.1.15 on 2026-03-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0032_service_episode_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceepisode',
            name='consent_to_aggregate_reporting',
            field=models.BooleanField(default=False, help_text='Whether this participant has consented to their de-identified data being included in aggregate funder reports for this program.'),
        ),
        migrations.AlterField(
            model_name='serviceepisode',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When active service began. Auto-set to enrolled_at on creation if blank.', null=True),
        ),
    ]
