# Generated by Django 5.1.15 on 2026-03-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_consentevent_request_received_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('select', 'Dropdown'), ('select_other', 'Dropdown with Other option'), ('multi_select', 'Multi-select checkboxes'), ('multi_select_other', 'Multi-select with Other option'), ('date', 'Date'), ('number', 'Number')], default='text', max_length=20),
        ),
    ]
