# Generated by Django 5.1.15 on 2026-03-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0041_set_demographics_admin_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldgroup',
            name='collapsed_by_default',
            field=models.BooleanField(default=False, help_text="When checked, this group is collapsed on the participant info tab. Use for sensitive demographics that aren't needed for daily service delivery. This is a display preference — it does not restrict access to the data."),
        ),
    ]
