# Generated by Django 5.1.15 on 2026-02-21 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_partner_report_section_metric'),
        ('programs', '0008_funder_profiles'),
        ('reports', '0007_alter_reporttemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='fiscal_year_start_month',
            field=models.PositiveSmallIntegerField(default=4, help_text='1=Jan, 4=Apr (Ontario govt), 7=Jul, etc.'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('both', 'Bilingual')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='output_format',
            field=models.CharField(choices=[('tabular', 'Tables and charts'), ('narrative', 'Narrative with data'), ('mixed', 'Mixed — narrative and tables')], default='mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='period_alignment',
            field=models.CharField(choices=[('calendar', 'Calendar year (Jan-Dec)'), ('fiscal', 'Fiscal year (custom start month)'), ('grant', 'Grant period')], default='fiscal', help_text='How the reporting period aligns with the calendar.', max_length=20),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='period_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual'), ('custom', 'Custom')], default='annual', help_text='How often this report is produced.', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the reporting requirements.'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(help_text="Template name, e.g., 'Quarterly Outcomes Report'.", max_length=255),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Partner name, e.g., 'United Way Greater Toronto'.", max_length=255)),
                ('name_fr', models.CharField(blank=True, default='', help_text='French name (optional).', max_length=255)),
                ('partner_type', models.CharField(choices=[('funder', 'Funder'), ('network', 'Network / Collaboration'), ('board', 'Board of Directors'), ('regulator', 'Government / Regulator'), ('accreditation', 'Accreditation Body'), ('donor', 'Donor'), ('other', 'Other')], help_text='Type of reporting relationship.', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('grant_number', models.CharField(blank=True, help_text='Grant or contribution agreement number (if applicable).', max_length=100)),
                ('grant_period_start', models.DateField(blank=True, null=True)),
                ('grant_period_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programs', models.ManyToManyField(blank=True, help_text='Programs this partner funds or oversees. Leave empty for organisation-wide partners (e.g., board).', related_name='partners', to='programs.program')),
            ],
            options={
                'db_table': 'partners',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='The partner this report template belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='reports.partner'),
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_fr', models.CharField(blank=True, default='', max_length=255)),
                ('section_type', models.CharField(choices=[('metrics_table', 'Metrics Table'), ('demographic_summary', 'Demographic Summary'), ('narrative', 'Narrative / Written Section'), ('chart', 'Chart / Visualisation'), ('service_stats', 'Service Statistics')], max_length=20)),
                ('instructions', models.TextField(blank=True, help_text='Guidance for narrative sections (what to write about).')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.reporttemplate')),
            ],
            options={
                'db_table': 'report_sections',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ReportMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation', models.CharField(choices=[('count', 'Count of participants'), ('average', 'Average value'), ('average_change', 'Average change (intake to latest)'), ('percentage', 'Percentage of participants'), ('threshold_count', 'Count meeting threshold'), ('threshold_percentage', 'Percentage meeting threshold'), ('sum', 'Sum total')], help_text='How this metric should be aggregated in the report.', max_length=25)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, help_text='For threshold-based aggregation: the target value.', max_digits=10, null=True)),
                ('display_label', models.CharField(blank=True, help_text="Override label for this partner's terminology.", max_length=255)),
                ('display_label_fr', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_consortium_required', models.BooleanField(default=False, help_text='Whether this metric is required by a consortium standard schema.')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_usages', to='plans.metricdefinition')),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_metrics', to='reports.reporttemplate')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='reports.reportsection')),
            ],
            options={
                'db_table': 'report_metrics',
                'ordering': ['sort_order'],
            },
        ),
    ]
