# Generated by Django 5.1.15 on 2026-02-21 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_reporttemplate_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OversightReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(help_text="Human-readable label, e.g. 'Q1 2026'.", max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('metrics_json', models.JSONField(help_text='All computed metrics: alerts_raised, alerts_resolved, median_resolution_days, active_at_quarter_end, notes_recorded, active_participants, active_staff, aging_alerts, pending_reviews, program_breakdown.')),
                ('overall_status', models.CharField(choices=[('ROUTINE', 'Routine'), ('NOTABLE', 'Notable')], default='ROUTINE', max_length=10)),
                ('notable_triggers', models.JSONField(blank=True, default=list, help_text='List of trigger descriptions that caused NOTABLE status.')),
                ('narrative', models.TextField(blank=True, default='', help_text='Management narrative added when status is NOTABLE.')),
                ('no_aging_alerts', models.BooleanField(default=True)),
                ('no_pending_reviews', models.BooleanField(default=True)),
                ('no_program_concentration', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_external', models.BooleanField(default=False, help_text='External version suppresses counts under 5.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_oversight_reports', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_oversight_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oversight_report_snapshots',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('oversight', 'Safety Oversight Report'), ('funder_report', 'Funder Report')], max_length=50)),
                ('frequency', models.CharField(choices=[('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('annually', 'Annually')], max_length=20)),
                ('due_date', models.DateField(help_text='Next due date for this report.')),
                ('reminder_days_before', models.PositiveIntegerField(default=14, help_text='Days before due date to start showing dashboard banner.')),
                ('banner_shown_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_schedules', to=settings.AUTH_USER_MODEL)),
                ('notify_users', models.ManyToManyField(blank=True, help_text='Users who receive reminders. If empty, all admins are notified.', related_name='report_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_schedules',
                'ordering': ['due_date'],
            },
        ),
    ]
