# Generated by Django 5.1.15 on 2026-02-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_oversight_report_snapshot_and_schedule'),
        ('reports', '0010_cleanup_partner_nonnull_remove_programs'),
    ]

    operations = [
    ]
