# Generated by Django 5.1.15 on 2026-02-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_merge_20260221_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsection',
            name='section_type',
            field=models.CharField(choices=[('metrics_table', 'Metrics Table'), ('demographic_summary', 'Demographic Summary'), ('narrative', 'Narrative / Written Section'), ('chart', 'Chart / Visualisation'), ('service_stats', 'Service Statistics'), ('standards_alignment', 'Standards Alignment (CIDS)')], max_length=20),
        ),
    ]
