# Generated by Django 5.1.15 on 2026-03-03 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_secureexportlink_individual_client_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='secureexportlink',
            name='agency_notes',
            field=models.TextField(blank=True, default='', help_text='Agency context notes accompanying this export.'),
        ),
        migrations.AddField(
            model_name='secureexportlink',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secureexportlink',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exports', to=settings.AUTH_USER_MODEL),
        ),
    ]
