# Generated by Django 5.1.15 on 2026-03-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_secureexportlink_agency_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='suppression_threshold',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Standard (< 5)'), (10, 'Conservative (< 10)')], default=5, help_text="Minimum cell count for demographic breakdowns. Cells below this threshold are displayed as '< N'. Standard (< 5) aligns with CIHI Pan-Canadian De-Identification Guidelines."),
        ),
    ]
