# Generated by Django 5.1.15 on 2026-03-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_rename_funder_to_standard_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportschedule',
            name='report_type',
            field=models.CharField(choices=[('oversight', 'Safety Oversight Report'), ('standard_report', 'Standard Report')], max_length=50),
        ),
        migrations.AlterField(
            model_name='secureexportlink',
            name='export_type',
            field=models.CharField(choices=[('client_data', 'Participant Data'), ('metrics', 'Metric Report'), ('standard_report', 'Standard Report'), ('individual_client', 'Individual Client Export'), ('session_report', 'Session Report')], max_length=50),
        ),
    ]
