# Generated by Django 5.1.15 on 2026-03-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_alter_reportschedule_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='taxonomy_system',
            field=models.CharField(
                blank=True,
                choices=[
                    ('iris_plus', 'IRIS+'),
                    ('sdg', 'SDG'),
                    ('cids_iris', 'CIDS / IRIS+'),
                    ('united_way', 'United Way'),
                    ('phac', 'Public Health Agency of Canada'),
                    ('provincial', 'Provincial'),
                    ('esdc', 'ESDC'),
                    ('custom', 'Custom'),
                ],
                default='',
                help_text=(
                    'Which external taxonomy framework this report uses for its '
                    'standards alignment appendix (e.g., IRIS+, SDG, United Way). '
                    'Leave blank if no taxonomy appendix is needed.'
                ),
                max_length=50,
            ),
        ),
    ]
